---
repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: 🐶 Ruff Linter
        language: system
        types: [python]
        entry: uv run --locked ruff check --fix
        require_serial: true
        stages: [commit, push, manual]
      - id: ruff-format
        name: 🐶 Ruff Formatter
        language: system
        types: [python]
        entry: uv run --locked ruff format
        require_serial: true
        stages: [commit, push, manual]
      - id: check-ast
        name: 🐍 Check Python AST
        language: system
        types: [python]
        entry: uv run --locked check-ast
      - id: check-case-conflict
        name: 🔠 Check for case conflicts
        language: system
        entry: uv run --locked check-case-conflict
      - id: check-docstring-first
        name: ℹ️  Check docstring is first
        language: system
        types: [python]
        entry: uv run --locked check-docstring-first
      - id: check-json
        name: ｛ Check JSON files
        language: system
        types: [json]
        entry: uv run --locked check-json
      - id: check-merge-conflict
        name: 💥 Check for merge conflicts
        language: system
        types: [text]
        entry: uv run --locked check-merge-conflict
      - id: check-toml
        name: ✅ Check TOML files
        language: system
        types: [toml]
        entry: uv run --locked check-toml
      - id: check-yaml
        name: ✅ Check YAML files
        language: system
        types: [yaml]
        entry: uv run --locked check-yaml
      - id: end-of-file-fixer
        name: ⮐  Fix End of Files
        language: system
        types: [text]
        entry: uv run --locked end-of-file-fixer
        stages: [commit, push, manual]
      - id: uv-lock
        name: 📜 Check uv lockfile
        language: system
        entry: uv lock --check
        pass_filenames: false
        always_run: true
      - id: pylint
        name: 🌟 Starring code with pylint
        language: system
        types: [python]
        entry: uv run --locked pylint
      - id: trailing-whitespace
        name: ✄  Trim Trailing Whitespace
        language: system
        types: [text]
        entry: uv run --locked trailing-whitespace-fixer
        stages: [commit, push, manual]
      - id: yamllint
        name: 🎗 Check YAML files with yamllint
        language: system
        types: [yaml]
        entry: uv run --locked yamllint
