[project]
name = "disabled-parking"
version = "0.0.0"
description = "A tool to fetch and upload disabled parking data to NIPKaart."
requires-python = ">=3.11,<4.0"
authors = [{ name = "NIPKaart", email = "hello@nipkaart.nl" }]
maintainers = [{ name = "Klaas Schoute", email = "hello@student-techlife.com" }]
license = "MIT"
readme = "README.md"
keywords = ["disabled", "parking", "nipkaart", "locations", "api"]
dependencies = [
  "pymysql>=1.1.0,<2.0.0",
  "python-dotenv>=1.0.0,<2.0.0",
  "pytz>=2023.3,<2024.0",
  "requests>=2.31.0,<3.0.0",
]

[project.urls]
Homepage = "https://github.com/nipkaart/disabled-parking"
Repository = "https://github.com/nipkaart/disabled-parking"
Documentation = "https://github.com/nipkaart/disabled-parking"

[dependency-groups]
cities = [
  "antwerpen>=1.0.0,<2.0.0",
  "arnhem>=0.1.0,<0.2.0",
  "brussel>=0.2.1,<0.3.0",
  "dresden>=0.2.1,<0.3.0",
  "dusseldorf>=1.0.0,<2.0.0",
  "eindhoven>=4.0.0,<5.0.0",
  "hamburg>=3.0.0,<4.0.0",
  "koeln>=0.3.1,<0.4.0",
  "liege>=1.0.0,<2.0.0",
  "namur>=1.0.0,<2.0.0",
  "odp-amsterdam>=6.0.0,<7.0.0",
  "async-timeout>=4,<6",
]
dev = [
  "pre-commit==3.8.0",
  "pre-commit-hooks==4.6.0",
  "pylint==3.3.9",
  "ruff==0.16.4",
  "yamllint==1.38.0",
]

[tool.uv]
package = false
default-groups = ["cities", "dev"]

[tool.pylint.BASIC]
good-names = [
  "_",
  "ex",
  "fp",
  "i",
  "id",
  "j",
  "k",
  "on",
  "Run",
  "T",
]

[tool.pylint."MESSAGES CONTROL"]
disable= [
  "too-few-public-methods",
  "too-many-arguments",
  "duplicate-code",
  "format",
  "unsubscriptable-object",
  "broad-except",
]

[tool.pylint.SIMILARITIES]
ignore-imports = true

[tool.pylint.FORMAT]
max-line-length = 88

[tool.pylint.DESIGN]
max-attributes = 20

[tool.ruff]
target-version = "py311"
lint.select = ["ALL"]
lint.ignore = [
  "CPY001", # Copyright is documented in LICENSE, not individual Python files
  "ANN401", # Opinioated warning on disallowing dynamically typed expressions
  "D203", # Conflicts with other rules
  "D213", # Conflicts with other rules
  "D417", # False positives in some occasions
  "PLR2004", # Just annoying, not really useful
  "T201", # Allow the use of print()

  # Conflicts with the Ruff formatter
  "COM812",
  "ISC001",
]

[tool.ruff.lint.flake8-pytest-style]
mark-parentheses = false
fixture-parentheses = false
