"""Exercise the locked package parsers, municipal mappings and local writer."""
# Copyright (c) 2026 NIPKaart
# ruff: noqa: PT009, PT027

from __future__ import annotations

import json
import subprocess
import sys
import tempfile
import unittest
from dataclasses import replace
from pathlib import Path
from unittest.mock import patch

from app.cities.provider import CityProvider
from app.export import write_records
from app.records import MunicipalRecord, capacity, identifier, orientation

FIXTURES = Path(__file__).parent / "fixtures"
ROOT = Path(__file__).resolve().parents[1]


def sample(city: str) -> dict:
    """Load a captured upstream fixture without network access."""
    return json.loads((FIXTURES / f"{city}.json").read_text(encoding="utf-8"))


class MappingTests(unittest.TestCase):
    """Check expected source values rather than snapshots generated by the adapter."""

    def test_all_locked_package_fixtures(self) -> None:
        """Every package model can feed the shared record without a database."""
        cases = {
            "amsterdam": ("113364485189", 1, "Akersingel", 52.353, 4.776),
            "antwerpen": ("42044", 1, None, 51.204, 4.392),
            "arnhem": ("96", None, "G.A. van Nispenstraat", 51.992, 5.894),
            "brussel": (
                "13b70cf5f967267f1ea88d2352ec66d43a841258",
                1,
                "Aarlenstraat, 63",
                50.842,
                4.374,
            ),
            "dresden": ("1", 1, None, 51.029, 13.742),
            "dusseldorf": (
                "a29702e7-94ae-4556-8e83-b57e8368f7c9",
                4,
                "Paul-Thomas-Straße 35",
                51.170,
                6.852,
            ),
            "eindhoven": (
                "b124abb045f038a12a255e410ccfceb49dba7c77",
                1,
                "Marconilaan",
                51.450,
                5.458,
            ),
            "hamburg": ("7460", 1, "Steenwisch 105", 53.583, 9.947),
            "koeln": ("1", 1, None, 50.882, 7.080),
            "liege": (
                "cba258ed55c9c207f5bd4b9db97053be72f99eb7",
                1,
                "quai Saint-Paul de Sinçay 103, 4031",
                50.603,
                5.605,
            ),
            "namur": ("2172", None, "Place de l'Ecole des Cadets", 50.466, 4.875),
        }
        for name, expected in cases.items():
            with self.subTest(city=name):
                city = CityProvider().provide_city(name)
                records = [
                    city.normalize(item) for item in city.source_items(sample(name))
                ]
                self.assertEqual(len(records), 1 if name == "eindhoven" else 2)
                record = records[0]
                self.assertEqual(
                    (record.external_id, record.number, record.street), expected[:3]
                )
                self.assertAlmostEqual(record.latitude, expected[3], places=3)
                self.assertAlmostEqual(record.longitude, expected[4], places=3)
                self.assertTrue(record.legacy_id.startswith(city.source_id + "-"))

    def test_unknown_zero_and_full_identity(self) -> None:
        """Do not replace unknown or zero capacity, or shorten Hamburg's source ID."""
        for name in ("brussel", "dresden", "liege", "hamburg"):
            city = CityProvider().provide_city(name)
            item = city.source_items(sample(name))[0]
            for count in (None, 0):
                with self.subTest(city=name, count=count):
                    self.assertEqual(
                        city.normalize(replace(item, number=count)).number, count
                    )
        city = CityProvider().provide_city("hamburg")
        item = replace(city.source_items(sample("hamburg"))[0], spot_id="00017460")
        record = city.normalize(item)
        self.assertEqual(record.external_id, "00017460")
        self.assertTrue(record.legacy_id.endswith("-7460"))
        city = CityProvider().provide_city("liege")
        record = city.normalize(city.source_items(sample("liege"))[0])
        self.assertFalse(record.legacy_id.endswith(record.external_id))

    def test_restrictions_and_source_dates(self) -> None:
        """Retain package information that the legacy SQL mapping discarded."""
        city = CityProvider().provide_city("dresden")
        record = city.normalize(city.source_items(sample("dresden"))[0])
        self.assertEqual(
            record.source_attributes["usage_time"], "von 00:00 Uhr bis 24:00 Uhr"
        )
        self.assertIn("1978248", record.source_attributes["photo"])
        city = CityProvider().provide_city("dusseldorf")
        record = city.normalize(city.source_items(sample("dusseldorf"))[0])
        self.assertEqual(record.source_attributes["note"], "Stadtbad Niederheid")
        self.assertEqual(record.source_updated_at.isoformat()[:10], "2022-10-28")
        city = CityProvider().provide_city("amsterdam")
        record = city.normalize(city.source_items(sample("amsterdam"))[0])
        self.assertIsNone(record.source_updated_at)
        self.assertEqual(record.geometry_method, "vertex_average")
        for value in ("Schuin", "Vissengraat", "Visgraat"):
            self.assertEqual(orientation(value), "Visgraat")

    def test_direct_json_sources_and_filter(self) -> None:
        """Exercise the four adapters without packages using synthetic source rows."""
        geometry = {"coordinates": [[[4, 52], [6, 52], [6, 54], [4, 54]]]}
        cases = {
            "amersfoort": {
                "features": [
                    {
                        "geometry": geometry,
                        "properties": {
                            "AANTAL_PLAATSEN": 2,
                            "STRAATNAAM": "Teststraat",
                        },
                    }
                ]
            },
            "den haag": {
                "result": {
                    "records": [
                        {
                            "GUID": "{0001}",
                            "LAT": 53,
                            "LONG": 5,
                            "AANTALPLAATSEN": None,
                            "ORIENTATIE": "Dwars",
                        }
                    ]
                }
            },
            "groningen": {
                "features": [
                    {
                        "geometry": geometry,
                        "properties": {
                            "VakID": "0001",
                            "Straatnaam": None,
                            "Vakfunctie": "Invaliden_alg",
                        },
                    },
                    {"properties": {"Vakfunctie": "other"}},
                ]
            },
            "zoetermeer": {
                "features": [
                    {
                        "properties": {
                            "OBJECTID_1": "0001",
                            "lat": 53,
                            "lon": 5,
                            "plaatsen": 0,
                        }
                    }
                ]
            },
        }
        for name, payload in cases.items():
            with self.subTest(city=name):
                city = CityProvider().provide_city(name)
                records = [city.normalize(item) for item in city.source_items(payload)]
                self.assertEqual(len(records), 1)
                record = records[0]
                self.assertEqual((record.latitude, record.longitude), (53, 5))
                self.assertEqual(
                    record.number, {"amersfoort": 2, "zoetermeer": 0}.get(name)
                )
                if name == "amersfoort":
                    self.assertEqual(record.identity_method, "coordinate_hash")
                else:
                    self.assertEqual(record.external_id, "0001")

    def test_lossy_upstream_capacity_is_rejected(self) -> None:
        """Known parser truncation cannot silently become a valid export."""
        for name, field, value in (
            ("amsterdam", "aantal", 1.5),
            ("dusseldorf", "anzahl", "100 Stellplätze"),
        ):
            payload = sample(name)
            payload["features"][0]["properties"][field] = value
            with self.subTest(city=name), self.assertRaises(ValueError):
                CityProvider().provide_city(name).source_items(payload)

    def test_invalid_values_fail(self) -> None:
        """Reject bad coordinates and lossy coercion before writing."""
        for value in (-1, 1.5, "NaN", "Infinity", True):
            with self.subTest(value=value), self.assertRaises((ValueError, TypeError)):
                capacity(value)
        self.assertEqual(identifier("0001"), "0001")
        for latitude, longitude in ((91, 5), (52, 181), (float("nan"), 5)):
            with self.subTest(latitude=latitude), self.assertRaises(ValueError):
                MunicipalRecord(
                    external_id="1",
                    legacy_id="old-1",
                    latitude=latitude,
                    longitude=longitude,
                    number=None,
                )


class WriterTests(unittest.TestCase):
    """Exercise local output and failure boundaries with real normalization."""

    def test_export_metadata_and_atomic_failure(self) -> None:
        """A failed export leaves the previous draft intact without temporary files."""
        city = CityProvider().provide_city("hamburg")
        records = [
            city.normalize(item) for item in city.source_items(sample("hamburg"))
        ]
        with tempfile.TemporaryDirectory() as directory:
            output = Path(directory) / "export.json"
            self.assertEqual(write_records(city, records, output), 2)
            original = output.read_bytes()
            result = json.loads(original)
            self.assertEqual(result["record_count"], 2)
            self.assertIsNone(result["complete"])
            self.assertIsNone(result["retrieved_at"])
            self.assertIn("exported_at", result)
            self.assertNotIn("visibility", result["records"][0])
            with self.assertRaises(ValueError):
                write_records(city, [records[0], records[0]], output)
            with patch("app.export.MAX_RECORDS", 1), self.assertRaises(ValueError):
                write_records(city, records, output)
            with patch("app.export.MAX_BYTES", 1), self.assertRaises(ValueError):
                write_records(city, records, output)
            self.assertEqual(output.read_bytes(), original)
            self.assertEqual(list(Path(directory).iterdir()), [output])

    def test_malformed_cli_input_preserves_output(self) -> None:
        """Invalid source shape produces a nonzero exit without overwriting output."""
        with tempfile.TemporaryDirectory() as directory:
            source = Path(directory) / "source.json"
            output = Path(directory) / "output.json"
            source.write_text("{}", encoding="utf-8")
            output.write_text("previous", encoding="utf-8")
            result = subprocess.run(  # noqa: S603
                [
                    sys.executable,
                    "export.py",
                    "--city",
                    "hamburg",
                    "--input",
                    str(source),
                    "--output",
                    str(output),
                ],
                cwd=ROOT,
                capture_output=True,
                text=True,
                check=False,
            )
            self.assertEqual(result.returncode, 1)
            self.assertIn("Export failed:", result.stderr)
            self.assertEqual(output.read_text(encoding="utf-8"), "previous")

    def test_cli_without_database_or_network(self) -> None:
        """Run the actual entry point with connection attempts explicitly forbidden."""
        with tempfile.TemporaryDirectory() as directory:
            output = Path(directory) / "export.json"
            code = (
                "import runpy, socket; from unittest.mock import patch; "
                "from contextlib import ExitStack; stack = ExitStack(); "
                "stack.enter_context(patch('pymysql.connect', "
                "side_effect=AssertionError('database'))); "
                "stack.enter_context(patch.object(socket.socket, 'connect', "
                "side_effect=AssertionError('network'))); "
                "runpy.run_path('export.py', run_name='__main__')"
            )
            result = subprocess.run(  # noqa: S603
                [
                    sys.executable,
                    "-c",
                    code,
                    "--city",
                    "hamburg",
                    "--input",
                    str(FIXTURES / "hamburg.json"),
                    "--output",
                    str(output),
                ],
                cwd=ROOT,
                capture_output=True,
                text=True,
                check=False,
            )
            self.assertEqual(result.returncode, 0, result.stderr)
            self.assertEqual(json.loads(output.read_text())["record_count"], 2)
            self.assertIn("completeness has not been verified", result.stdout)


if __name__ == "__main__":
    unittest.main()
