# Docker compose STACK file
version: "3"

services:
  # Scrape Eindhoven Service
  nipkaart_eindhoven:
    image: parking-eindhoven:latest
    networks:
      - backend
    deploy:
      restart_policy:
        condition: on-failure

# Networks
networks:
  backend:
    driver: overlay